spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/callisto?serverTimezone=UTC
    username: callisto
    password: tygh
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
server:
  port: 8666