spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/callisto?serverTimezone=UTC
    username: callisto
    password: tygh
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  # kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  # consul
  cloud:
    consul:
      enabled: true
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-path: /actuator/health
        health-check-interval: 30s
        health-check-timeout: 5s
server:
  port: 8666

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true