basePath: /
definitions:
  models.Notice:
    description: 공지사항 모델
    properties:
      created_at:
        type: string
      notice_contents:
        example: notice_contents
        type: string
      notice_id:
        type: integer
      notice_title:
        example: notice_title
        type: string
      profile_id:
        example: profile_id
        type: string
      updated_at:
        type: string
    required:
    - profile_id
    type: object
host: localhost:5001
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /admin/notice:
    post:
      consumes:
      - application/json
      description: Create a new notice.
      parameters:
      - description: Notice
        in: body
        name: notice
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Notice'
      summary: create a new notice
      tags:
      - Notice
    put:
      consumes:
      - application/json
      description: Update notice.
      parameters:
      - description: Notice
        in: body
        name: notice
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
      summary: update notice
      tags:
      - Notice
  /admin/notice/{id}:
    delete:
      consumes:
      - application/json
      description: Delete notice by given ID.
      parameters:
      - description: Notice ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ok
          schema:
            type: string
      summary: delete notice by given ID
      tags:
      - Notice
    get:
      consumes:
      - application/json
      description: Get notice by ID
      parameters:
      - description: Notice ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Notice'
      summary: Get a notice by ID
  /admin/notices:
    get:
      consumes:
      - application/json
      description: Get notices
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Notice'
      summary: Get notices
swagger: "2.0"
